version: '3'

services:
  database:
    image: "postgres:13"
    restart: "always"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: ${MAIN_DATABASE}, ${SHADOW_DATABASE}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./docker/pg-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - nginx
    expose: ['5432']

  api:
    image: "node:14"
    restart: "always"
    working_dir: /usr/app
    depends_on:
      - database
    environment:
      DATABASE_URL: "postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@database:5432/${MAIN_DATABASE}"
      SHADOW_DATABASE_URL: "postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@database:5432/${SHADOW_DATABASE}"
      ROOT_DATABASE_URL: "postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@database:5432/postgres"
      PORT: 3002
      APP_ENV: dev
      WAIT_HOSTS: database:5432
      WAIT_HOSTS_TIMEOUT: 300
    volumes:
      - ./api:/usr/app
      - /usr/app/node_modules
      - ./docker/wait-postgresql:/usr/scripts
    expose: ['3002']
    networks:
      - nginx
    command:  bash -c "yarn && /usr/scripts/wait && yarn run migrate && yarn run migrate:shadow && yarn dev"

  webapp:
    image: "node:14"
    restart: "always"
    working_dir: /usr/app
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - "API_HTTP_URL=http://localhost:${API_PORT}"
      - "API_WS_URL=ws://localhost:${API_PORT}"
    volumes:
      - ./client:/usr/app
      - /usr/app/node_modules
      - /usr/app/.nuxt
      - webapp_static:/user/app/static
    command: bash -c "yarn && yarn run dev"
    networks:
      - nginx
    expose: ['3000']

  admin:
    image: "node:14"
    restart: "always"
    working_dir: /usr/app
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3001
      - APP_ENV=dev
      - "API_HTTP_URL=http://localhost:${API_PORT}"
      - "API_WS_URL=ws://localhost:${API_PORT}"
    volumes:
      - ./admin:/usr/app
      - /usr/app/node_modules
      - /usr/app/.nuxt
      - admin_static:/user/app/static
    command: bash -c "yarn && yarn run dev"
    networks:
      - nginx
    expose: ['3001']

  nginx:
    networks:
      - nginx
    image: nginx:alpine
    ports:
      - 9100:9100
      - 9101:9101
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./docker/nginx/dev/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx:/var/log/nginx
      - webapp_static:/usr/share/nginx/html/webapp
      - admin_static:/usr/share/nginx/html/admin
    depends_on:
      - webapp
      - admin
      - api

networks:
  nginx:

volumes:
  webapp_static: {}
  admin_static: {}
